services:
  postgres:
    image: postgres:14
    container_name: pecantv_db
    environment:
      POSTGRES_DB: pecantv
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - pecantv_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    container_name: pecantv_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pecantv.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - pecantv_network

  data_loader:
    build:
      context: ./scripts
      dockerfile: Dockerfile
    container_name: pecantv_data_loader
    volumes:
      - ./scripts:/app
      - ./scripts/credentials.json:/app/credentials.json
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/credentials.json
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - pecantv_network

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: pecantv_api
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app
    environment:
      - DATABASE_URL=postgresql+psycopg2://postgres:postgres@postgres:5432/pecantv
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - pecantv_network

volumes:
  postgres_data:

networks:
  pecantv_network:
    driver: bridge 