[build]
  command = "cd api && pip install -r requirements.txt"
  publish = "api"
  functions = "api/functions"

[build.environment]
  PYTHON_VERSION = "3.11"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/main/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/main/:splat"
  status = 200

[functions]
  directory = "api/functions"

[functions.main]
  runtime = "python3.11" 