#!/bin/bash

echo "🚀 Cloudflare Images Setup for PecanTV"
echo "======================================"
echo ""

echo "📋 Prerequisites:"
echo "1. You need a Cloudflare account"
echo "2. Your domain (pecantv.com) must be added to Cloudflare"
echo "3. You need API access to Cloudflare"
echo ""

echo "🔧 Step 1: Cloudflare Dashboard Setup"
echo "-------------------------------------"
echo "1. Log into your Cloudflare dashboard"
echo "2. Go to 'Images' in the left sidebar"
echo "3. Click 'Get started with Cloudflare Images'"
echo "4. Choose a plan (Free tier includes 100,000 images/month)"
echo ""

echo "🌐 Step 2: DNS Configuration"
echo "----------------------------"
echo "In your Cloudflare DNS settings for pecantv.com, add:"
echo ""
echo "Type: A"
echo "Name: images"
echo "IPv4 address: 192.0.2.1 (or your server IP)"
echo "Proxy status: Proxied (orange cloud)"
echo ""
echo "Type: CNAME"
echo "Name: images-resize"
echo "Target: images.pecantv.com"
echo "Proxy status: Proxied (orange cloud)"
echo ""

echo "⚙️ Step 3: Image Resizing Setup"
echo "-------------------------------"
echo "1. Go to 'Speed > Optimization' in Cloudflare dashboard"
echo "2. Scroll down to 'Image Resizing'"
echo "3. Enable 'Image Resizing' and 'Polish'"
echo "4. Set Polish to 'Lossless' or 'Lossy' (recommended for photos)"
echo ""

echo "🔑 Step 4: API Token Setup"
echo "--------------------------"
echo "1. Go to 'My Profile > API Tokens' in Cloudflare dashboard"
echo "2. Click 'Create Token'"
echo "3. Use 'Custom token' template"
echo "4. Set permissions:"
echo "   - Zone:Zone:Read"
echo "   - Zone:Zone Settings:Edit"
echo "   - Account:Cloudflare Images:Edit"
echo "5. Set zone resources to 'Include: pecantv.com'"
echo "6. Create token and copy it"
echo ""

echo "📝 Step 5: Environment Configuration"
echo "----------------------------------"
echo "Add these to your api/.env file:"
echo ""
echo "CLOUDFLARE_ACCOUNT_ID=your_account_id"
echo "CLOUDFLARE_API_TOKEN=your_api_token"
echo "CLOUDFLARE_IMAGES_DOMAIN=images.pecantv.com"
echo ""

echo "🧪 Step 6: Testing"
echo "------------------"
echo "After setup, test with:"
echo "python3 test_cloudflare_images.py"
echo ""

echo "📊 Expected Results:"
echo "-------------------"
echo "✅ images.pecantv.com responds (not 404)"
echo "✅ Image optimization reduces file sizes by 30-70%"
echo "✅ Faster loading times from Cloudflare's CDN"
echo "✅ Automatic WebP conversion for modern browsers"
echo ""

echo "🔗 Useful URLs:"
echo "--------------"
echo "Cloudflare Dashboard: https://dash.cloudflare.com"
echo "Cloudflare Images: https://dash.cloudflare.com/images"
echo "Image Resizing Docs: https://developers.cloudflare.com/images/image-resizing/"
echo ""

echo "⚠️  Important Notes:"
echo "------------------"
echo "1. DNS changes may take up to 24 hours to propagate"
echo "2. Image Resizing requires a paid plan (not available on free tier)"
echo "3. For free tier, you can still use Cloudflare Images for new uploads"
echo "4. Test thoroughly before deploying to production"
echo ""

echo "🎯 Next Steps:"
echo "-------------"
echo "1. Complete the Cloudflare dashboard setup"
echo "2. Configure DNS records"
echo "3. Set up API tokens"
echo "4. Update environment variables"
echo "5. Test the setup"
echo "6. Deploy to production"
echo ""

echo "📞 Need Help?"
echo "------------"
echo "Cloudflare Support: https://support.cloudflare.com"
echo "Image Resizing Docs: https://developers.cloudflare.com/images/image-resizing/"
echo ""

echo "✅ Setup guide complete!" 